all:
  children:
    servers:
      hosts:
        # 示例服务器配置，请根据实际情况修改
        server1:
          ansible_host: 192.168.1.10
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        server2:
          ansible_host: 192.168.1.11
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        server3:
          ansible_host: 192.168.1.12
          ansible_user: admin
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      vars:
        # 全局变量
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_timeout: 30
        ansible_command_timeout: 30 