all:
  children:
    servers:
      hosts:
        # 示例服务器配置，请根据实际情况修改
        server1:
          ansible_host: 193.0.20.98
          ansible_user: ddapiserver
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python
        server2:
          ansible_host: 193.0.20.120
          ansible_user: user
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python
        server3:
          ansible_host: 193.0.30.94
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          ansible_python_interpreter: /usr/bin/python
      vars:
        # 全局变量
        ansible_ssh_timeout: 30
        ansible_command_timeout: 30
        # 使用Python 2.7
        ansible_python_interpreter: /usr/bin/python 