---
- name: 收集系统基本信息
  raw: |
    echo "=== 系统信息 ==="
    uname -a
    echo "=== 操作系统信息 ==="
    cat /etc/os-release 2>/dev/null || cat /etc/redhat-release 2>/dev/null || echo "无法获取系统信息"
    echo "=== 内核版本 ==="
    uname -r
    echo "=== 架构 ==="
    uname -m
  register: system_info
  tags: [asset, basic_info]

- name: 获取CPU信息
  raw: |
    echo "=== CPU信息 ==="
    cat /proc/cpuinfo | grep -E "model name|processor|physical id|core id" | head -20
    echo "=== CPU核心数 ==="
    nproc 2>/dev/null || grep -c processor /proc/cpuinfo 2>/dev/null || echo "无法获取CPU核心数"
  register: cpu_info
  tags: [asset, cpu]

- name: 获取内存信息
  raw: |
    echo "=== 内存信息 ==="
    free -h 2>/dev/null || echo "无法获取内存信息"
    echo "=== 内存详细信息 ==="
    cat /proc/meminfo | head -10
  register: memory_info
  tags: [asset, memory]

- name: 获取磁盘信息
  raw: |
    echo "=== 磁盘使用情况 ==="
    df -h
    echo "=== 磁盘分区信息 ==="
    fdisk -l 2>/dev/null | head -20 || echo "无法获取分区信息"
  register: disk_info
  tags: [asset, disk]

- name: 获取网络接口信息
  raw: |
    echo "=== 网络接口 ==="
    ip addr show 2>/dev/null || ifconfig 2>/dev/null || echo "无法获取网络信息"
    echo "=== 路由表 ==="
    ip route show 2>/dev/null || route -n 2>/dev/null || echo "无法获取路由信息"
  register: network_info
  tags: [asset, network]

- name: 获取系统负载
  raw: |
    echo "=== 系统负载 ==="
    uptime
    echo "=== 进程信息 ==="
    ps aux | head -10
  register: load_info
  tags: [asset, load]

- name: 获取运行的服务
  raw: |
    echo "=== 运行的服务 ==="
    systemctl list-units --type=service --state=running 2>/dev/null | head -20 || service --status-all 2>/dev/null | head -20 || echo "无法获取服务信息"
  register: services_info
  tags: [asset, services]

- name: 获取已安装的软件包数量
  raw: |
    echo "=== 软件包信息 ==="
    if command -v dpkg >/dev/null 2>&1; then
      echo "Debian/Ubuntu系统"
      dpkg -l | wc -l
    elif command -v rpm >/dev/null 2>&1; then
      echo "RHEL/CentOS系统"
      rpm -qa | wc -l
    else
      echo "未知包管理器"
    fi
  register: packages_count
  tags: [asset, packages]

- name: 获取系统用户信息
  raw: |
    echo "=== 用户信息 ==="
    cat /etc/passwd | wc -l
    echo "=== 当前登录用户 ==="
    who
  register: users_count
  tags: [asset, users]

- name: 获取开放端口
  raw: |
    echo "=== 开放端口 ==="
    ss -tuln 2>/dev/null | head -20 || netstat -tuln 2>/dev/null | head -20 || echo "无法获取端口信息"
  register: open_ports
  tags: [asset, ports]

- name: 获取系统时间
  raw: |
    echo "=== 系统时间 ==="
    date
    echo "=== 时区信息 ==="
    timedatectl 2>/dev/null || date +%Z
  register: system_time
  tags: [asset, time] 